python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name ArticularyWordRecognition \
    --records_file Classification_records.xls \
    --data_dir ./datasets/ArticularyWordRecognition \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2 \
    --gpu 3

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name AtrialFibrillation \
    --records_file Classification_records.xls \
    --data_dir ./datasets/AtrialFibrillation \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 4 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2 \
    --no_attn_pooling

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name BasicMotions \
    --records_file Classification_records.xls \
    --data_dir ./datasets/BasicMotions \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 4 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2 \
    --no_attn_pooling

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name CharacterTrajectories \
    --records_file Classification_records.xls \
    --data_dir ./datasets/CharacterTrajectories \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 4 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2 \
    --no_attn_pooling

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name Cricket \
    --records_file Classification_records.xls \
    --data_dir ./datasets/Cricket \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.001 \
    --patch_size 8 \
    --stride 8 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 4 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2 \
    --no_attn_pooling

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name Epilepsy \
    --records_file Classification_records.xls \
    --data_dir ./datasets/Epilepsy \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 4 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 0 \
    --no_stat_prompt \

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name ERing \
    --records_file Classification_records.xls \
    --data_dir ./datasets/ERing \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 3 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name FingerMovements \
    --records_file Classification_records.xls \
    --data_dir ./datasets/FingerMovements \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 3 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name Libras \
    --records_file Classification_records.xls \
    --data_dir ./datasets/Libras \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --seed 42 \
    --gpu 3 \
    --gpt_layers 6 \
    --num_mamba_layers 2

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name NATOPS \
    --records_file Classification_records.xls \
    --data_dir ./datasets/NATOPS \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --seed 42 \
    --gpu 5 \
    --num_mamba_layers 0 \
    --no_stat_prompt \

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name PhonemeSpectra \
    --records_file Classification_records.xls \
    --data_dir ./datasets/PhonemeSpectra \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 16 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --seed 42 \
    --gpu 5 \
    --num_mamba_layers 0 \
    --no_stat_prompt \

python src/main.py \
    --output_dir experiments \
    --comment "classification from Scratch" \
    --name RacketSports \
    --records_file Classification_records.xls \
    --data_dir ./datasets/RacketSports \
    --data_class tsra \
    --pattern TRAIN \
    --val_pattern TEST \
    --epochs 100 \
    --lr 0.0005 \
    --patch_size 8 \
    --stride 2 \
    --optimizer AdamW \
    --d_model 768 \
    --pos_encoding learnable \
    --task classification \
    --key_metric accuracy \
    --gpu 3 \
    --seed 42 \
    --gpt_layers 6 \
    --num_mamba_layers 2


